version: '3.4'

services:
  easylifeapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  easy-life-frontend:
    ports:
      - "3000:3000"

  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  backend-mailer:
    ports:
      - "5001:3002"